### ISSUE TITLE
Why not obatining the RGB video by Quest3 directly?

### ISSUE THREAD

**Issue by huaihailv** [Ericcsr/ARCap#4]
I haven't fully figured out the purpose of adding an extra RealSense RGB-D camera.  Is it because of the depth information? If not, why not directly use the Quest 3 to capture video information?

**Comment by Ericcsr** [comment]
Hi, thanks for your interest in our work! Sadly Meta doesn't allow developer to access raw rgb images due to privacy concerns, as for depth images, although we can obtain them from depth API the resolution is too low (100x100)
